// The Gentle Stoic Parent — knowledge base (ES / EN)
const L = (es, en) => ({ es, en });

export const FAMILY = { adults: ['Juan', 'Christine'], kids: [{ name: 'Sophia', age: 7 }, { name: 'Isaac', age: 5 }] };

// dow: 1 Mon … 5 Fri. Evening roles cross: dinner = drop-off parent, bath & stories = home parent.
export const WEEK = {
  1: { take: 'Juan', stay: 'Christine', bf: 'b1', pm: L('Judo 6:30 · ballet 7:00', 'Judo 6:30 · ballet 7:00') },
  2: { take: 'Christine', stay: 'Juan', bf: 'b2', pm: null },
  3: { take: 'Juan', stay: 'Christine', bf: 'b3', pm: L('Ballet 7:00', 'Ballet 7:00') },
  4: { take: 'Christine', stay: 'Juan', bf: 'b4', pm: null },
  5: { take: 'Juan', stay: 'Christine', bf: 'b5', pm: null },
};

export const MORNING = [
  { id: 'm0655', t: '6:55', anchor: true, ti: L('Los adultos se levantan', 'Grown-ups get up'),
    l: [['both', 'Unos minutos antes que los niños: agua, respirar, café. Un adulto tranquilo es el primer paso de una mañana tranquila.', 'A few minutes before the kids: water, a breath, coffee. A calm grown-up is the first step of a calm morning.']] },
  { id: 'm0700', t: '7:00', ti: L('Sophia se despierta', 'Sophia wakes up'),
    l: [['stay', 'Despierta a Sophia con voz baja y abre las cortinas.', 'Wakes Sophia softly and opens the curtains.'], ['take', 'Ducha hasta las 7:25.', 'Showers until 7:25.'], ['sophia', 'Se viste primero.', 'Gets dressed first.']],
    say: L('Buenos días. La cocina nos está esperando.', 'Good morning. The kitchen is waiting for us.') },
  { id: 'm0710', t: '7:10', ti: L('El rato de cocina de Sophia', "Sophia's kitchen time"),
    l: [['stay', 'Cocina con ella el desayuno del menú del día. Cuida el fuego y le recuerda qué partes queman.', 'Cooks the menu breakfast with her. Minds the stove and reminds her which parts are hot.'], ['sophia', 'Bate, sirve y pone la mesa.', 'Whisks, serves and sets the table.']] },
  { id: 'm0725', t: '7:25', anchor: true, ti: L('Isaac se despierta · llegan los dos', 'Isaac wakes · both grown-ups in'),
    l: [['take', 'Ya duchado, despierta a Isaac.', 'Freshly showered, wakes Isaac.'], ['isaac', 'Elige el cuento o pódcast del desayuno. Es su trabajo.', "Picks the breakfast story or podcast. It's his job."]],
    say: L('Hoy tú eliges la historia del desayuno.', 'You get to pick the breakfast story today.') },
  { id: 'm0730', t: '7:30', ti: L('Isaac se prepara', 'Isaac gets ready'),
    l: [['take', 'Lo acompaña sin hacerlo por él: baño, ropa, tender la cama.', 'Walks beside him, not for him: bathroom, clothes, bed made.'], ['stay', 'Termina el desayuno con Sophia.', 'Finishes breakfast with Sophia.']],
    say: L('Tus calcetines están esperando en la silla.', 'Your socks are waiting on the chair.'),
    stuck: L('Describe lo que ves en vez de dar órdenes. Ofrece dos opciones: «¿primero camiseta o pantalón?»', 'Describe what you see instead of giving orders. Offer two choices: “shirt first or pants first?”') },
  { id: 'm0745', t: '7:45', ti: L('Desayuno en familia', 'Family breakfast'),
    l: [['all', 'Los cuatro sentados. Suena la historia de Isaac. Sin pantallas.', "All four at the table. Isaac's story is playing. No screens."]] },
  { id: 'm0800', t: '8:00', ti: L('Primero recogemos', 'Tidy first'),
    l: [['kids', 'Cada uno lleva su plato y su vaso al fregadero y deja la pijama en el cesto.', 'Each carries their plate and cup to the sink and puts pajamas in the hamper.'], ['both', 'Los adultos también llevan lo suyo. Nadie recoge por otro.', 'Grown-ups carry theirs too. Nobody tidies for someone else.']],
    say: L('Tu plato todavía está en la mesa. Seguimos cuando esté en el fregadero.', "Your plate is still on the table. We move on once it's in the sink.") },
  { id: 'm0805', t: '8:05', ti: L('Dientes, zapatos, mochilas', 'Teeth, shoes, backpacks'),
    l: [['take', 'Dientes y zapatos con los niños. Las mochilas se prepararon anoche.', 'Teeth and shoes with the kids. Backpacks were packed last night.'], ['stay', 'Limpia la mesa.', 'Wipes the table.']],
    say: L('Nuestros zapatos ya están junto a la puerta.', 'Our shoes are waiting by the door.') },
  { id: 'm0815', t: '8:15', anchor: true, ti: L('¡Salimos!', 'Off we go!'),
    l: [['take', 'Lleva a los niños. Si hubo un imprevisto, quedan diez minutos de colchón hasta las 8:25.', "Drives the kids. If something went wrong, there's a ten-minute cushion until 8:25."], ['stay', 'Ahora le toca su ducha y su rato.', "Now it's their shower and their own time."]] },
];

export const EVENING = [
  { id: 'e1800', t: '18:00', ti: L('Se prepara la cena', 'Dinner gets made'),
    l: [['dinner', 'Cocina. Los niños ayudan si quieren.', 'Cooks. The kids help if they want to.'], ['bath', 'Juego y conexión con los niños. Nada de trabajo ni limpieza.', 'Play and connection with the kids. No work, no chores.']] },
  { id: 'e1830', t: '18:30', ti: L('Cena en familia · 30 minutos', 'Family dinner · 30 minutes'),
    l: [['all', 'Sentados juntos, sin pantallas. Con una pantalla delante, los niños miran y no comen.', "Seated together, no screens. With a screen in front of them, kids watch and don't eat."]],
    stuck: L('Si a las 7:00 no terminaron, se retira el plato con calma. Para eso está el snack de las 7:40.', "If they haven't finished by 7:00, calmly clear the plate. That's what the 7:40 snack is for.") },
  { id: 'e1900', t: '19:00', ti: L('Todo vuelve a su casa', 'Everything goes home'),
    l: [['all', 'Cada uno lleva su plato. Cinco minutos para que los juguetes vuelvan a su cesto, con los adultos ayudando.', 'Everyone carries their plate. Five minutes for toys to go back to their baskets, grown-ups helping.']],
    say: L('Los bloques se quieren ir a dormir a su cesto.', 'The blocks want to go to sleep in their basket.') },
  { id: 'e1910', t: '19:10', ti: L('Baño', 'Bath'),
    l: [['bath', 'Baño de los niños.', "Kids' bath."], ['dinner', 'Cierra la cocina y deja las mochilas junto a la puerta.', 'Closes the kitchen and leaves backpacks by the door.']] },
  { id: 'e1930', t: '19:30', anchor: true, ti: L('Empieza el ritmo lento', 'The slow rhythm begins'),
    l: [['all', 'Luces bajas, voz lenta, pocas palabras. Pijamas. La ropa sucia al cesto.', 'Low lights, slow voices, few words. Pajamas. Dirty clothes in the hamper.']] },
  { id: 'e1940', t: '19:40', ti: L('La última comida del día', 'The last snack of the day'),
    l: [['dinner', 'Ofrece el snack puente: fruta, pan o leche.', 'Offers the bridge snack: fruit, bread or milk.'], ['bath', 'Dientes justo después.', 'Teeth right after.']],
    say: L('Esta es la última comida de hoy. ¿Tu barriga quiere algo?', 'This is the last food for today. Does your tummy want something?') },
  { id: 'e1950', t: '19:50', ti: L('La ropa de mañana', "Tomorrow's clothes"),
    l: [['kids', 'Cada uno deja su ropa de mañana en la silla.', "Each child lays tomorrow's clothes on the chair."]] },
  { id: 'e1955', t: '19:55', ti: L('Cuentos', 'Stories'),
    l: [['bath', 'Cada niño en su cama. El adulto se sienta en medio y lee un libro elegido por cada uno.', 'Each child in their own bed. The grown-up sits in between and reads one book each child chose.'], ['dinner', 'Tiempo libre para sí.', 'Free time for themselves.']] },
  { id: 'e2015', t: '20:15', ti: L('Luces fuera', 'Lights out'),
    l: [['bath', 'Apaga la luz. La misma frase de cierre y tres respiraciones juntos.', 'Turns off the light. The same closing words and three breaths together.']],
    say: L('El día terminó. Tu cuerpo ya puede descansar.', 'The day is done. Your body can rest now.') },
  { id: 'e2030', t: '20:30', anchor: true, ti: L('Dormidos · cinco minutos de equipo', 'Asleep · five team minutes'),
    l: [['both', '¿Qué funcionó hoy? ¿Qué ajustamos mañana?', 'What worked today? What do we adjust tomorrow?']] },
];

// Tarde: quien NO llevó a los niños por la mañana (pickup = stay) los recoge a las 4:30.
// 20 min de camino + 30–40 min de juego y snack a la salida del colegio.
export const AFTERNOON = [
  { id: 'a1610', t: '16:10', ti: L('Sale a recoger', 'Time to leave for pick-up'),
    l: [['pickup', 'Sale de casa hacia el colegio (20 min). Lleva agua y el snack.', 'Leaves for school (20 min). Brings water and the snack.'], ['dinner', 'Sigue con lo suyo. La cena empieza a las 6:00.', 'Carries on with their own things. Dinner starts at 6:00.']] },
  { id: 'a1630', t: '16:30', anchor: true, ti: L('Recogida en el colegio', 'School pick-up'),
    l: [['pickup', 'Recoge a Sophia e Isaac. Saludo tranquilo, sin preguntas de examen.', 'Picks up Sophia and Isaac. A calm hello, no quiz questions.'], ['kids', 'Juegan y comen su snack unos 30–40 minutos.', 'Play and eat their snack for about 30–40 minutes.']],
    say: L('Qué gusto verte. Tenemos un rato para jugar antes de ir a casa.', 'So good to see you. We have a little while to play before we go home.') },
  { id: 'a1710', t: '17:10', ti: L('Rumbo a casa', 'Heading home'),
    l: [['pickup', 'Aviso de cinco minutos antes; luego, al coche. Camino de 20 minutos.', 'A five-minute heads-up first, then to the car. A 20-minute ride.']],
    say: L('Cinco minutos más y el parque se despide hasta mañana.', 'Five more minutes and the park says goodbye until tomorrow.'),
    stuck: L('Si no quieren irse, no negocies: describe lo que pasa. «El coche nos está esperando.» Ofrece dos opciones: «¿Vamos saltando o de puntillas?»', "If they don't want to leave, don't negotiate: describe what's happening. “The car is waiting for us.” Offer two choices: “Shall we hop or tiptoe?”") },
  { id: 'a1730', t: '17:30', anchor: true, ti: L('Llegamos a casa', 'Home again'),
    l: [['kids', 'Mochilas en su sitio, loncheras al fregadero, manos lavadas.', 'Backpacks in their place, lunchboxes to the sink, hands washed.'], ['pickup', 'Juego tranquilo y conexión hasta las 6:00.', 'Quiet play and connection until 6:00.'], ['dinner', 'Termina lo suyo; a las 6:00 empieza la cena.', 'Wraps up; dinner starts at 6:00.']] },
];

// Lunes y miércoles: recogida con merienda fuerte y directo a la actividad.
export const AFTERNOON_MW = [
  { id: 'p1610', t: '16:10', ti: L('Sale a recoger', 'Time to leave for pick-up'),
    l: [['pickup', 'Sale hacia el colegio (20 min) con la merienda fuerte y la ropa de la actividad.', 'Leaves for school (20 min) with the proper snack and the activity clothes.']] },
  { id: 'p1630', t: '16:30', anchor: true, ti: L('Recogida · merienda fuerte', 'Pick-up · proper snack'),
    l: [['pickup', 'Recoge a los niños y les da una merienda fuerte antes de la actividad.', 'Picks up the kids and gives them a real snack before the activity.'], ['kids', 'Comen y juegan un rato.', 'Eat and play for a while.']],
    say: L('Qué gusto verte. Primero comemos, luego nos vamos.', 'So good to see you. First we eat, then we go.') },
  { id: 'p1710', t: '17:10', ti: L('Rumbo a la actividad', 'Off to the activity'),
    l: [['pickup', 'Aviso de cinco minutos y en marcha. Todo va en la mochila desde la mañana.', 'Five-minute heads-up and off we go. Everything has been in the bag since morning.']] },
];

export const EVENING_MW = [
  { id: 'w1830', t: '18:30', ti: L('Isaac: baño y pijama', 'Isaac: bath and pajamas'),
    l: [['bath', 'Lunes: Isaac llega de judo y va directo al baño. Miércoles: baño a la misma hora.', 'Monday: Isaac comes home from judo, straight to the bath. Wednesday: bath at the same time.'], ['dinner', 'Calienta la cena que se dejó preparada.', 'Warms up the dinner prepared in advance.']] },
  { id: 'w1900', t: '19:00', ti: L('Llega Sophia del ballet', 'Sophia home from ballet'), l: [] },
  { id: 'w1905', t: '19:05', ti: L('Cena en familia · 25 minutos', 'Family dinner · 25 minutes'),
    l: [['all', 'Juntos, sin pantallas. Después, cada uno lleva su plato.', 'Together, no screens. Then everyone carries their plate.']] },
  { id: 'w1930', t: '19:30', anchor: true, ti: L('Ducha y dientes', 'Shower and teeth'),
    l: [['bath', 'Ducha rápida de Sophia.', 'Quick shower for Sophia.'], ['dinner', 'Dientes de Isaac.', "Isaac's teeth."]] },
  { id: 'w1945', t: '19:45', ti: L('Casi listos', 'Almost there'),
    l: [['kids', 'Dientes de Sophia, ropa de mañana en la silla, juguetes a su cesto.', "Sophia's teeth, tomorrow's clothes on the chair, toys in the basket."]] },
  { id: 'w1955', t: '19:55', ti: L('Un solo cuento compartido', 'One shared story'), l: [] },
  { id: 'w2015', t: '20:15', ti: L('Luces fuera', 'Lights out'), l: [],
    say: L('El día terminó. Tu cuerpo ya puede descansar.', 'The day is done. Your body can rest now.') },
  { id: 'w2030', t: '20:30', anchor: true, ti: L('Dormidos · cinco minutos de equipo', 'Asleep · five team minutes'),
    l: [['both', '¿Qué funcionó hoy? ¿Qué ajustamos mañana?', 'What worked today? What do we adjust tomorrow?']] },
];

export const QUOTES = [
  L('No controlamos la mañana. Controlamos cómo la recibimos.', "We don't control the morning. We control how we meet it."),
  L('Respira antes de hablar. La calma se contagia más rápido que la prisa.', 'Breathe before you speak. Calm spreads faster than hurry.'),
  L('Hoy no necesitas ser perfecto. Necesitas ser el mismo equipo.', "Today you don't need to be perfect. You need to be the same team."),
  L('No nos perturban las cosas, sino lo que pensamos de ellas. — Epicteto', 'We are disturbed not by things, but by our views of them. — Epictetus'),
  L('Observa más de lo que hablas.', 'Observe more than you speak.'),
  L('Sufrimos más en la imaginación que en la realidad. — Séneca', 'We suffer more in imagination than in reality. — Seneca'),
  L('Tienes poder sobre tu mente, no sobre lo que pasa afuera. — Marco Aurelio', 'You have power over your mind, not outside events. — Marcus Aurelius'),
  L('Un niño que se siente confiado aprende a confiar en sí mismo.', 'A child who feels trusted learns to trust themselves.'),
  L('Pregunta una vez. Después, deja espacio.', 'Ask once. Then leave space.'),
  L('No hace falta ser perfectos. Hace falta ser el mismo equipo todos los días.', "We don't need to be perfect. We need to be the same team every day."),
  L('La vida no tiene que ser difícil.', "Life doesn't have to be hard."),
  L('Los hogares tranquilos los construyen padres estables.', 'Calm homes are built by steady parents.'),
  L('La calma va antes que la corrección.', 'Calm comes before correction.'),
  L('La presencia enseña más que los sermones.', 'Presence teaches more than lectures.'),
  L('La confianza crea seguridad más rápido que el control.', 'Trust builds confidence faster than control.'),
  L('La sabiduría crece cuando hay espacio para pensar.', 'Wisdom grows when there is space to think.'),
  L('Pausa. Observa. Respira.', 'Pause. Observe. Breathe.'),
  L('No se trata de controlar la vida, sino de recibirla bien.', 'Not by controlling life, but by meeting it well.'),
  L('No criamos niños obedientes. Criamos niños sabios.', "We're not raising obedient children. We're raising wise ones."),
  L('Enseñamos a recibir la vida, no a escapar de ella.', 'We model how to meet life, not how to escape it.'),
];

// The core of our system — Modern Stoic Parenting
export const CORE = {
  name: L('Crianza estoica moderna', 'Modern Stoic Parenting'),
  tagline: L('Un regreso tranquilo a la estabilidad', 'A quiet return to steadiness'),
  promise: L('No promete niños fáciles. Promete padres más estables.', "It doesn't promise easy children. It promises steadier parents."),
  within: L('El padre estoico y gentil guía desde adentro.', 'The gentle stoic parent leads from within.'),
  pillars: [
    { id: 'p-calm', t: L('La calma va antes que la corrección', 'Calm comes before correction') },
    { id: 'p-presence', t: L('La presencia enseña más que los sermones', 'Presence teaches more than lectures') },
    { id: 'p-trust', t: L('La confianza crea seguridad más rápido que el control', 'Trust builds confidence faster than control') },
    { id: 'p-space', t: L('La sabiduría crece cuando hay espacio para pensar', 'Wisdom grows when there is space to think') },
  ],
  practice: L(['Pausa', 'Observa', 'Respira'], ['Pause', 'Observe', 'Breathe']),
  choose: L(['Puedes elegir la calma.', 'Puedes guiar con claridad.', 'Puedes crear un hogar seguro, estable e intencional.'], ['You can choose calm.', 'You can lead with clarity.', 'You can create a home that feels safe, steady and intentional.']),
  reminder: L('La vida no tiene que ser difícil.', "Life doesn't have to be hard."),
};

// cat: principle · agreement · situation · story · breakfast  (routine & phrase entries are derived from the steps)
export const ENTRIES = [
  { id: 'p-invite', cat: 'principle', t: L('Crianza estoica moderna', 'Modern Stoic Parenting'),
    s: L('Un regreso tranquilo a la estabilidad. El núcleo de nuestro sistema.', 'A quiet return to steadiness. The core of our system.'),
    b: L([
      'Nadie nos enseña a ser padres. Heredamos hábitos, repetimos patrones, reaccionamos bajo presión, y después nos preguntamos por qué todo se siente tan difícil.',
      'Muchos días se sienten apurados. Ruidosos. Pesados. Demasiadas decisiones, demasiada culpa, muy poca calma. Y en medio de todo empezamos a creer una mentira: que criar tiene que sentirse como sobrevivir. No es así.',
      'La crianza estoica moderna es una invitación a bajar el ritmo, recuperar el control y guiar a la familia desde la calma en lugar del caos. No siendo perfectos. No aprendiendo más técnicas. Siendo estables.',
      'Porque los hogares tranquilos los construyen padres estables.',
      'No se trata de criar niños «obedientes». Se trata de criar niños sabios, y volvernos más sabios nosotros en el proceso.',
    ], [
      'Nobody teaches us how to be parents. We inherit habits, repeat patterns, react under pressure, and then wonder why everything feels so hard.',
      'Most days feel rushed. Loud. Heavy. Too many decisions, too much guilt, too little calm. And somewhere in the middle of it all we start to believe a lie: that parenting is supposed to feel like survival. It isn\'t.',
      'Modern Stoic Parenting is an invitation to slow down, regain control and lead your family from a place of calm instead of chaos. Not by becoming perfect. Not by learning more techniques. By becoming steady.',
      'Because calm homes are built by steady parents.',
      'This is not about raising “obedient” children. It\'s about raising wise ones, and becoming wiser ourselves in the process.',
    ]), k: 'filosofia philosophy manifiesto nucleo core calma steady estable invitacion invitation moderna modern' },
  { id: 'p-within', cat: 'principle', t: L('Guiar desde adentro', 'Lead from within'),
    s: L('No corre a arreglarlo todo. Pausa, observa, respira.', "Doesn't rush to fix everything. Pauses, observes, breathes."),
    b: L([
      'El padre estoico y gentil entiende cuatro cosas: la calma va antes que la corrección; la presencia enseña más que los sermones; la confianza crea seguridad más rápido que el control; la sabiduría crece cuando hay espacio para pensar.',
      'No corre a arreglarlo todo. Hace una pausa. Observa. Respira.',
      'Modela cómo recibir la vida, no cómo escapar de ella.',
      'Y así enseña algo mucho más valioso que las reglas: cómo enfrentar la incomodidad sin miedo y los retos sin pánico.',
    ], [
      'A gentle stoic parent understands four things: calm comes before correction; presence teaches more than lectures; trust builds confidence faster than control; wisdom grows when there is space to think.',
      "They don't rush to fix everything. They pause. They observe. They breathe.",
      'They model how to meet life, not how to escape it.',
      'And in doing so they teach something far more valuable than rules: how to face discomfort without fear, and challenges without panic.',
    ]), k: 'adentro within liderar lead pausa pause observar observe respirar breathe arreglar fix miedo fear panico panic' },
  { id: 'p-presence', cat: 'principle', t: L('La presencia enseña más que los sermones', 'Presence teaches more than lectures'),
    s: L('Lo que hacemos enseña más que lo que decimos.', 'What we do teaches more than what we say.'),
    b: L([
      'Los niños aprenden mirando cómo vivimos: cómo recibimos una mañana difícil, cómo hablamos cuando estamos cansados, cómo reparamos cuando nos equivocamos.',
      'Menos palabras, más presencia. Sentarse a su lado, mirar a los ojos, bajar a su altura.',
      'Si sentimos la urgencia de explicar, primero preguntamos: ¿lo necesita escuchar o lo necesita ver?',
    ], [
      'Children learn by watching how we live: how we meet a hard morning, how we speak when we are tired, how we repair when we get it wrong.',
      'Fewer words, more presence. Sit beside them, meet their eyes, come down to their level.',
      'When we feel the urge to explain, we first ask: do they need to hear it, or see it?',
    ]), k: 'presencia presence sermon lecture modelar model ejemplo example explicar explain' },
  { id: 'p-space', cat: 'principle', t: L('Espacio para pensar', 'Space to think'),
    s: L('La sabiduría crece cuando hay espacio para pensar.', 'Wisdom grows when there is space to think.'),
    b: L([
      'No llenamos cada silencio. Una pausa larga no es un problema: es donde el niño piensa.',
      'Hacemos una pregunta y esperamos. No rescatamos a la primera señal de incomodidad.',
      'Lo mismo vale para nosotros: antes de responder, un respiro.',
    ], [
      "We don't fill every silence. A long pause isn't a problem: it's where the child thinks.",
      "We ask one question and wait. We don't rescue at the first sign of discomfort.",
      'The same goes for us: before responding, one breath.',
    ]), k: 'espacio space silencio silence pensar think pausa pause esperar wait rescatar rescue' },
  { id: 'p-reallife', cat: 'principle', t: L('Crianza para la vida real', 'Parenting for real life'),
    s: L('Mañanas desordenadas, resistencia, cansancio.', 'Messy mornings, resistance, exhaustion.'),
    b: L([
      'Esto es para las mañanas desordenadas. Para la resistencia. Para el cansancio.',
      'Para los momentos en que sientes que estás fallando, incluso cuando no es así.',
      'La crianza estoica moderna no promete niños fáciles. Promete padres más estables.',
      'Y los padres estables crean hogares tranquilos: no porque todo salga bien, sino porque saben mantenerse firmes cuando no sale.',
    ], [
      "This is for messy mornings. For resistance. For exhaustion.",
      "For the moments when you feel you're failing, even when you're not.",
      "Modern Stoic Parenting doesn't promise easy children. It promises steadier parents.",
      "And steady parents create calm homes: not because everything goes right, but because they know how to stay grounded when it doesn't.",
    ]), k: 'vida real real life fallar failing culpa guilt cansancio exhaustion tired resistencia resistance desorden messy' },
  { id: 'p-choose', cat: 'principle', t: L('Esta es tu invitación', 'This is your invitation'),
    s: L('Dejar de criar desde la urgencia.', 'Stop parenting from urgency.'),
    b: L([
      'Dejar de criar desde la urgencia. Dejar de delegar nuestra confianza. Dejar de creer que el caos es normal.',
      'Puedes elegir la calma. Puedes guiar con claridad. Puedes crear un hogar que se sienta seguro, estable e intencional.',
      'No controlando la vida, sino recibiéndola bien.',
      'Y este es tu recordatorio: la vida no tiene que ser difícil.',
    ], [
      'To stop parenting from urgency. To stop outsourcing your confidence. To stop believing chaos is normal.',
      'You can choose calm. You can lead with clarity. You can create a home that feels safe, steady and intentional.',
      'Not by controlling life, but by meeting it well.',
      "And this is your reminder: life doesn't have to be hard.",
    ]), k: 'urgencia urgency prisa rush caos chaos elegir choose claridad clarity intencional intentional confianza confidence' },
  { id: 'p-calm', cat: 'principle', t: L('La calma va antes que la corrección', 'Calm comes before correction'),
    s: L('Primero se regula, después se enseña.', 'Regulate first, teach second.'),
    b: L([
      'Nunca empezamos enseñando ni corrigiendo. Empezamos regulando. Un niño activado no puede reflexionar.',
      'Conexión antes que cognición: voz lenta, pocas palabras, presencia cálida, sin urgencia.',
      'En la práctica: respira antes de hablar, baja la voz, muévete más despacio. El adulto se regula primero.',
    ], [
      "We never begin with teaching or correcting. We begin with regulation. A child who is activated can't reflect.",
      'Connection before cognition: slow voice, few words, warm presence, no urgency.',
      'In practice: breathe before you speak, lower your voice, move more slowly. The grown-up regulates first.',
    ]), k: 'regular regulation berrinche tantrum enojo angry grito shout' },
  { id: 'p-observe', cat: 'principle', t: L('Observar en lugar de juzgar', 'Observe instead of judge'),
    s: L('Describimos lo que vemos. Sin críticas, sin vergüenza.', 'We describe what we see. No criticism, no shame.'),
    b: L([
      'Nombramos la realidad con observaciones neutras. Nunca criticamos ni avergonzamos.',
      'En lugar de «¡Apúrate!», decimos: «Nuestros zapatos ya están junto a la puerta.»',
      'Una observación deja espacio para que el niño decida el siguiente paso.',
    ], [
      'We name reality with neutral observations. We never criticise or shame.',
      'Instead of “Hurry up!”, we say: “Our shoes are waiting by the door.”',
      'An observation leaves room for the child to choose the next step.',
    ]), k: 'ordenes commands apurate hurry prisa rush' },
  { id: 'p-trust', cat: 'principle', t: L('La confianza antes que el control', 'Trust before control'),
    s: L('La confianza crea seguridad más rápido que el control.', 'Trust builds confidence faster than control.'),
    b: L([
      'Evitamos explicar de más, corregir de más y proteger de más.',
      'Permitimos errores pequeños, silencio, incomodidad y tiempo para pensar.',
      'La confianza crece cuando un niño se siente confiado, no administrado.',
    ], [
      'We avoid over-explaining, over-correcting and over-protecting.',
      'We allow small mistakes, silence, discomfort and time to think.',
      'Confidence grows when a child feels trusted, not managed.',
    ]), k: 'autonomia independence hacer por el do it for them rescatar rescue' },
  { id: 'p-socratic', cat: 'principle', t: L('Preguntas que abren puertas', 'Questions that open doors'),
    s: L('Una sola pregunta. Nunca un examen.', 'One question. Never a quiz.'),
    b: L([
      'Las preguntas invitan a darse cuenta: «¿Qué notas?», «¿Cómo se siente eso?», «¿Qué camino se siente mejor?», «¿Qué pasó?»',
      'Evitamos los «¿por qué?» y las preguntas que ya traen la respuesta dentro.',
      'Hacemos una pregunta y dejamos espacio. No interrogamos.',
    ], [
      'Questions invite awareness: “What do you notice?”, “How does that feel?”, “Which way feels better?”, “What happened?”',
      'We avoid “why” questions and questions that already contain the answer.',
      "We ask one question and leave space. We don't interrogate.",
    ]), k: 'socratico socratic preguntar ask por que why' },
  { id: 'p-stories', cat: 'principle', t: L('Cuentos en lugar de sermones', 'Stories instead of lectures'),
    s: L('El cuento enseña. El adulto no.', 'The story teaches. The parent does not.'),
    b: L([
      'Los cuentos funcionan como espejos: el niño se ve sin sentirse expuesto ni corregido.',
      'Son paralelos al problema, no idénticos. Nunca explicamos la lección ni terminamos con «la moraleja es…».',
      'Si algo se repite muchas noches, se habla de día, con un cuento.',
    ], [
      'Stories work as mirrors: the child sees themselves without feeling exposed or corrected.',
      'They run parallel to the problem, not identical. We never explain the lesson or end with “the moral is…”.',
      'If something keeps happening at night, we talk about it in the daytime, through a story.',
    ]), k: 'sermon lecture cuento story moraleja moral' },
  { id: 'p-wisdom', cat: 'principle', t: L('Criar para la sabiduría', 'Parent for wisdom'),
    s: L('La meta no es la conducta de hoy. Es la brújula interna.', "The goal isn't today's behaviour. It's the inner compass."),
    b: L([
      'No buscamos obediencia inmediata. Buscamos crecimiento interno.',
      'Los padres modelan la conducta en lugar de controlarla.',
      'Lo que el niño descubre por sí mismo se queda más que cualquier consejo.',
    ], [
      "We aren't after immediate obedience. We're after inner growth.",
      'Parents model behaviour instead of controlling it.',
      'What a child discovers alone stays longer than any advice.',
    ]), k: 'obediencia obedience control compass brujula' },
  { id: 'p-coach', cat: 'principle', t: L('Cómo acompañamos una situación', 'How we meet a situation'),
    s: L('Reencuadre, postura, observación, una pregunta, un cuento.', 'Reframe, posture, observation, one question, a story.'),
    b: L([
      '1 · Reencuadre: ¿qué está pasando debajo de la conducta? Casi siempre es cansancio, hambre, prisa o una emoción grande.',
      '2 · Postura: el adulto se regula primero. Más lento, menos palabras, guiar en vez de empujar.',
      '3 · Observación neutra: cambiamos la orden por lo que vemos.',
      '4 · Una pregunta: solo una, para abrir. Nunca un interrogatorio.',
      '5 · Un cuento: la herramienta principal, contado después, con calma.',
      '6 · Una pregunta de reflexión, opcional. Sin explicar el significado.',
    ], [
      "1 · Reframe: what's happening beneath the behaviour? It's almost always tiredness, hunger, hurry or a big feeling.",
      '2 · Posture: the grown-up regulates first. Slower, fewer words, guide rather than push.',
      '3 · Neutral observation: swap the command for what we see.',
      '4 · One question: just one, to open. Never an interrogation.',
      '5 · A story: the main tool, told later, calmly.',
      '6 · One optional reflection question. Without explaining the meaning.',
    ]), k: 'metodo method pasos steps coaching' },
  { id: 'p-storycraft', cat: 'principle', t: L('Cómo contamos un cuento', 'How we tell a story'),
    s: L('Siete pasos para un cuento que funcione como espejo.', 'Seven steps for a story that works as a mirror.'),
    b: L([
      'Personajes: humanos o animales humanizados (hablan, van a la escuela, tienen familia). Los objetos no hablan ni sienten; la naturaleza solo existe.',
      '1 · Personajes en los que el niño se reconozca. 2 · Sus fortalezas primero: lo natural de la infancia no es malo.',
      '3 · El problema aparece solo, mostrando cómo se siente el cuerpo. Sin castigo ni culpa.',
      '4 · Un adulto reflexivo (abuela, abuelo, maestra) hace una sola pregunta y no explica.',
      '5 · Un niño prueba algo distinto por curiosidad. Sin premio ni castigo.',
      '6 · Nada mágico pasa: afuera casi nada cambia, adentro sí.',
      '7 · Final con emoción, no con lección. La última frase se siente en paz.',
      'Tono: calmado, cálido, lento. Con pausas y respiraciones, casi como una meditación guiada.',
    ], [
      "Characters: humans or humanised animals (they talk, go to school, have families). Objects don't talk or feel; nature simply exists.",
      "1 · Characters the child recognises. 2 · Strengths first: natural childhood behaviour isn't bad.",
      '3 · The problem arrives naturally, showing how the body feels. No punishment, no blame.',
      '4 · A reflective adult (grandmother, grandfather, teacher) asks one question and explains nothing.',
      '5 · One child tries something different out of curiosity. No reward, no punishment.',
      '6 · Nothing magical happens: outside barely changes, inside does.',
      '7 · End with feeling, not a lesson. The last sentence feels peaceful.',
      'Tone: calm, warm, slow. With pauses and breaths, almost like guided mindfulness.',
    ]), k: 'narrar narrate escribir write cuento story' },

  { id: 'a-lead', cat: 'agreement', t: L('Quien lidera, lidera', 'Whoever leads, leads'),
    s: L('El otro no corrige delante de los niños.', "The other doesn't correct in front of the kids."),
    b: L(['El rol de hoy decide cómo se hace su parte. El otro no corrige delante de los niños. Si algo preocupa, se guarda para las 8:30.'], ["Today's role decides how its part is done. The other parent doesn't correct in front of the kids. Concerns wait until 8:30."]), k: 'rol role corregir correct pareja partner' },
  { id: 'a-725', cat: 'agreement', t: L('A las 7:25 estamos los dos', "At 7:25 we're both there"),
    s: L('Sin excepción, los cinco días.', 'No exceptions, all five days.'),
    b: L(['Sin excepción, los cinco días. El mismo apoyo en los días de Juan y en los de Christine.'], ["No exceptions, all five days. The same support on Juan's days and on Christine's."]), k: 'manana morning' },
  { id: 'a-tidy', cat: 'agreement', t: L('Primero recogemos, después seguimos', 'Tidy first, then we move on'),
    s: L('Nadie pasa al siguiente paso sin guardar lo suyo.', 'Nobody moves on until their own things are put away.'),
    b: L(['Nadie pasa al siguiente paso hasta guardar lo suyo: su plato, su pijama, sus juguetes. Los adultos también.'], ['Nobody moves to the next step until their own things are put away: plate, pajamas, toys. Grown-ups too.']), k: 'recoger tidy plato plate juguetes toys orden' },
  { id: 'a-dinner', cat: 'agreement', t: L('La cena es sagrada', 'Dinner is sacred'),
    s: L('Sin pantallas, sin trabajo. Los cuatro sentados.', 'No screens, no work. All four at the table.'),
    b: L(['Sin pantallas, sin trabajo y sin limpiar mientras se come. Los cuatro sentados.'], ['No screens, no work and no cleaning while we eat. All four at the table.']), k: 'pantallas screens tele tv celular phone cena dinner' },
  { id: 'a-team', cat: 'agreement', t: L('Cinco minutos de equipo', 'Five team minutes'),
    s: L('A las 8:30, con los niños dormidos. Sin culpas.', 'At 8:30, kids asleep. No blame.'),
    b: L(['A las 8:30, con los niños dormidos: ¿qué funcionó?, ¿qué ajustamos mañana? Sin culpas.', 'Los cambios al plan se deciden aquí, nunca delante de los niños.'], ['At 8:30, kids asleep: what worked? what do we adjust tomorrow? No blame.', 'Changes to the plan are decided here, never in front of the kids.']), k: 'equipo team pareja partner discutir argue' },
  { id: 'a-tag', cat: 'agreement', t: L('La palabra de relevo', 'The tag-out word'),
    s: L('«Relevo»: el otro toma tu lugar, sin comentarios.', '“Tag”: the other steps in, no comments.'),
    b: L(['Si uno pierde la paciencia, dice «relevo» y el otro toma su lugar sin comentarios.'], ['If one of us loses patience, they say “tag” and the other steps in, no comments.']), k: 'paciencia patience relevo tag grito shout' },
  { id: 'a-plan', cat: 'agreement', t: L('Un solo plan', 'One plan'),
    s: L('Si hay duda, gana lo que dice el plan. Dos semanas de prueba.', 'When in doubt, the plan wins. A two-week trial.'),
    b: L([
      'Vale igual para los dos. Si hay duda, gana lo que dice aquí, no quien tenga más energía en ese momento.',
      'Léanlo juntos una vez; después, úsenlo como consulta rápida para la parte que les toque.',
      'Dos semanas de prueba: sigan el plan tal cual antes de cambiar nada. Un hábito necesita tiempo.',
      'Colchón: el trayecto es de 20 minutos y la meta es llegar a las 8:45, así que el límite real es 8:25. Salir a las 8:15 deja diez minutos para los imprevistos.',
    ], [
      "It's the same for both of you. When in doubt, this plan wins, not whoever has more energy right then.",
      'Read it together once; after that, use it as a quick check for your part of the day.',
      'A two-week trial: follow it as written before changing anything. Habits need time.',
      'Cushion: the school run is 20 minutes and the goal is 8:45, so the real limit is 8:25. Leaving at 8:15 leaves ten minutes for surprises.',
    ]), k: 'plan prueba trial colchon cushion horario schedule' },

  { id: 'x-hungry', cat: 'situation', t: L('«Tengo hambre» después de los dientes', '“I\'m hungry” after teeth'),
    s: L('El snack de las 7:40 fue la última comida.', 'The 7:40 snack was the last food.'),
    b: L(['1. El snack de las 7:40 fue la última comida.', '2. Ofrece agua. Nada más.', '3. Mañana se revisa la cena en los cinco minutos de equipo.'], ['1. The 7:40 snack was the last food.', '2. Offer water. Nothing else.', '3. Tomorrow, review dinner in the team minutes.']),
    say: L('Tu barriga está pidiendo. El desayuno de mañana la va a esperar. ¿Quieres agua?', "Your tummy is asking. Tomorrow's breakfast will be waiting for it. Would you like water?"), k: 'hambre hungry comida food snack noche night' },
  { id: 'x-bed', cat: 'situation', t: L('Se levanta de la cama', 'Gets out of bed'),
    s: L('Acompañarlo de vuelta, siempre igual, sin enojo.', 'Walk them back, the same every time, without anger.'),
    b: L(['1. Acompáñalo de vuelta con pocas palabras, siempre igual, sin enojo.', '2. Si se repite muchas noches, se habla de día con un cuento.'], ['1. Walk them back with few words, the same every time, without anger.', '2. If it keeps happening, talk about it in the daytime, through a story.']),
    say: L('La luz ya está apagada y tu cuerpo sigue despierto. Vamos a tu cama.', "The light is off and your body is still awake. Let's go back to your bed."), k: 'dormir sleep cama bed noche night levanta' },
  { id: 'x-fight', cat: 'situation', t: L('Pelea o drama entre hermanos', 'Sibling fight or drama'),
    s: L('Respirar, separar sin culpables, una pregunta a cada uno.', 'Breathe, separate without blame, one question each.'),
    b: L(['1. El adulto respira primero.', '2. Separa si hace falta, sin buscar culpables.', '3. Una pregunta a cada uno, por turnos. Sin sermón.'], ['1. The grown-up breathes first.', '2. Separate if needed, without looking for blame.', '3. One question each, taking turns. No lecture.']),
    say: L('Veo a dos niños muy enojados. ¿Qué necesitas tú ahora?', 'I see two very upset kids. What do you need right now?'), k: 'pelea fight hermanos siblings pegar hit enojo angry llanto crying compartir share' },
  { id: 'x-late', cat: 'situation', t: L('La mañana se atrasa', 'The morning runs late'),
    s: L('El colchón existe para esto. Se recorta, nunca se grita.', "The cushion is there for this. Cut something, never shout."),
    b: L(['1. El colchón de diez minutos existe para esto.', '2. Se recorta algo, nunca se grita: la cama se tiende en la tarde.', '3. Si se complica el desayuno: plan B.'], ['1. The ten-minute cushion is there for this.', '2. Cut something, never shout: the bed gets made in the afternoon.', '3. If breakfast goes wrong: Plan B.']),
    say: L('El reloj dice que es hora de los zapatos.', "The clock says it's shoe time."), k: 'tarde late prisa rush vestirse dressed lento slow' },
  { id: 'x-plate', cat: 'situation', t: L('Un plato se queda en la mesa', 'A plate stays on the table'),
    s: L('No se recoge por el niño. Se nombra y se espera.', "Don't clear it for them. Name it and wait."),
    b: L(['1. No se recoge por el niño.', '2. Se nombra lo que se ve y se espera con calma.'], ["1. Don't clear it for them.", '2. Name what you see and wait calmly.']),
    say: L('Tu plato todavía está aquí. Seguimos cuando llegue al fregadero.', "Your plate is still here. We'll move on when it reaches the sink."), k: 'plato plate recoger tidy' },
  { id: 'x-patience', cat: 'situation', t: L('Un adulto pierde la paciencia', 'A grown-up loses patience'),
    s: L('«Relevo». No es un fracaso: es trabajar en equipo.', "“Tag”. It isn't failure: it's teamwork."),
    b: L(['1. Dice «relevo». El otro toma el rol sin comentarios ni miradas.', '2. Se habla a las 8:30, con calma. No es un fracaso: es trabajar en equipo.'], ['1. Say “tag”. The other takes over, no comments, no looks.', "2. Talk at 8:30, calmly. It isn't failure: it's teamwork."]), k: 'paciencia patience grito shout culpa guilt enojo angry' },

  { id: 'b1', cat: 'breakfast', t: L('Lunes · Avena con fruta y miel', 'Monday · Oatmeal with fruit & honey'),
    s: L('Sophia sirve la fruta y la miel. El adulto calienta la avena.', 'Sophia adds fruit and honey. The grown-up heats the oats.'), b: L([], []), dish: L('Avena con fruta y miel', 'Oatmeal with fruit & honey') },
  { id: 'b2', cat: 'breakfast', t: L('Martes · Huevos revueltos', 'Tuesday · Scrambled eggs'),
    s: L('Su especialidad: rompe y bate. El adulto cuida la sartén.', 'Her specialty: she cracks and whisks. The grown-up minds the pan.'), b: L([], []), dish: L('Huevos revueltos', 'Scrambled eggs') },
  { id: 'b3', cat: 'breakfast', t: L('Miércoles · Yogur con granola y fruta', 'Wednesday · Yogurt with granola & fruit'),
    s: L('Sin fuego. Día ligero antes del ballet.', 'No stove. A light day before ballet.'), b: L([], []), dish: L('Yogur con granola y fruta', 'Yogurt with granola & fruit') },
  { id: 'b4', cat: 'breakfast', t: L('Jueves · Tostadas con aguacate o queso', 'Thursday · Toast with avocado or cheese'),
    s: L('Sophia unta y sirve. El adulto maneja la tostadora.', 'Sophia spreads and serves. The grown-up runs the toaster.'), b: L([], []), dish: L('Tostadas con aguacate o queso', 'Toast with avocado or cheese') },
  { id: 'b5', cat: 'breakfast', t: L('Viernes · Panqueques', 'Friday · Pancakes'),
    s: L('Celebración de viernes. Sophia bate y sirve; el adulto voltea.', 'Friday treat. Sophia mixes and serves; the grown-up flips.'), b: L([], []), dish: L('Panqueques', 'Pancakes') },
  { id: 'b-planb', cat: 'breakfast', t: L('Plan B · cereal con leche y un plátano', 'Plan B · cereal with milk and a banana'),
    s: L('No es un fracaso: es la red de seguridad.', "Not a failure: it's the safety net."),
    b: L(['Siempre en casa, listo en cinco minutos. Si algo se quema, no hay regaño ni rescate: plan B, y mañana lo intenta otra vez.'], ['Always in the pantry, ready in five minutes. If something burns, no scolding and no rescue: Plan B, and she tries again tomorrow.']), k: 'quemar burn fallo fail' },
  { id: 'b-steps', cat: 'breakfast', t: L('Sophia en la cocina, por escalones', 'Sophia in the kitchen, step by step'),
    s: L('Su trabajo es con la comida, nunca con Isaac.', 'Her job is the food, never Isaac.'),
    b: L([
      'Un desayuno fijo por día: Sophia solo cocina, no tiene que decidir. Elegir y cocinar a la vez, a las siete de la mañana, es demasiado.',
      'Escalón 1 · ahora — Juntos: Sophia rompe, bate, sirve y pone la mesa. El adulto maneja el fuego.',
      'Escalón 2 — Ella cocina, el adulto al lado: remueve en la sartén; el adulto, a un brazo de distancia, habla poco.',
      'Escalón 3 — Ella sola: el adulto está en casa pero no en la cocina. Solo cuando el escalón 2 ya le sale fácil entre semana.',
      'Lo nuevo se practica el fin de semana.',
    ], [
      "One set breakfast per day: Sophia only cooks, she doesn't have to decide. Choosing and cooking at 7 a.m. is too much at once.",
      'Step 1 · now — Together: Sophia cracks, whisks, serves and sets the table. The grown-up handles the stove.',
      "Step 2 — She cooks, grown-up beside her: she stirs the pan; the grown-up is an arm's length away and says little.",
      'Step 3 — On her own: the grown-up is home but not in the kitchen. Only once step 2 comes easily on weekdays.',
      'New skills get practised at the weekend.',
    ]), k: 'cocinar cook sophia autonomia independence' },

  { id: 's-morning', cat: 'story', t: L('Las mañanas de Leo y Maya', 'Leo and Maya\'s mornings'),
    s: L('Para cuando las mañanas se escapan. Unos 4 minutos.', 'For when mornings slip away. About 4 minutes.'),
    b: L([
      '[NARRADOR | calmado, cálido, lento]',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'En una casa pequeña, al final de una calle con árboles, vivían dos hermanos: Leo y Maya.',
      'A Leo le encantaba observar el mundo. Las hormigas en fila. Las nubes que cambiaban de forma. La luz que entraba por la ventana.',
      'A Maya le encantaba jugar a imaginar. Con una manta hacía un barco. Con dos cucharas, una orquesta.',
      '[PAUSA: corta]',
      'Pero las mañanas se les escapaban. Mientras miraban y jugaban, el tiempo pasaba… y de pronto había que correr.',
      'Correr hacía que sus cuerpos se sintieran apretados. Salían de casa con el corazón rápido. Y deseaban que las mañanas duraran un poco más.',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'Una tarde, su abuela los encontró en el jardín.',
      '[ABUELA | suave, curiosa]',
      '«¿Cómo se sienten las mañanas cuando tienen tiempo… y cómo se sienten cuando no lo tienen?»',
      '[PAUSA: larga]',
      'Nadie respondió. La abuela tampoco dijo nada más.',
      'A la mañana siguiente, Maya se vistió primero. Nadie se lo pidió.',
      'Afuera, nada cambió. El sol salió igual. La calle estaba igual.',
      'Pero adentro, Maya se sentía lista.',
      'Y descubrió algo: ahora tenía tiempo. Sacó sus colores y pintó un árbol lleno de pájaros.',
      'En la escuela, sus amigos miraron su pintura con los ojos muy abiertos.',
      '[PAUSA: corta]',
      'Maya pensó que vestirse primero no le había quitado su juego. Le había dado más.',
      'Leo lo notó. Y a la mañana siguiente, él también eligió prepararse primero.',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'Esa mañana salieron de casa despacio. Con los hombros sueltos. Con tiempo para mirar una hormiga, y otra, y otra.',
      '[PAUSA: larga]',
    ], [
      '[NARRATOR | calm, warm, slow]',
      '[BREATH: slow inhale… slow exhale]',
      'In a small house at the end of a tree-lined street lived two siblings: Leo and Maya.',
      'Leo loved observing the world. Ants in a line. Clouds changing shape. The light coming through the window.',
      'Maya loved imaginative play. A blanket became a boat. Two spoons, an orchestra.',
      '[PAUSE: short]',
      'But their mornings slipped away. While they watched and played, time passed… and suddenly they had to run.',
      'Running made their bodies feel tight. They left home with quick hearts. And they wished mornings lasted a little longer.',
      '[BREATH: slow inhale… slow exhale]',
      'One afternoon, their grandmother found them in the garden.',
      '[GRANDMOTHER | soft, curious]',
      '“How do mornings feel when you have time… and how do they feel when you don\'t?”',
      '[PAUSE: long]',
      'Nobody answered. Grandmother said nothing more.',
      'The next morning, Maya got dressed first. Nobody asked her to.',
      'Outside, nothing changed. The sun rose the same. The street was the same.',
      'But inside, Maya felt ready.',
      'And she discovered something: now she had time. She took out her colours and painted a tree full of birds.',
      'At school, her friends looked at her painting with wide eyes.',
      '[PAUSE: short]',
      "Maya thought that getting ready first hadn't taken away her play. It had given her more.",
      'Leo noticed. And the following morning, he chose to get ready first too.',
      '[BREATH: slow inhale… slow exhale]',
      'That morning they left home slowly. Shoulders loose. With time to watch one ant, and another, and another.',
      '[PAUSE: long]',
    ]), reflect: L('¿Cómo se sintió la mañana de Maya cuando tuvo tiempo?', "How did Maya's morning feel when she had time?"), k: 'manana morning vestirse dressed prisa rush tarde late' },
  { id: 's-river', cat: 'story', t: L('Tomi, Lía y el columpio', 'Tomi, Lía and the swing'),
    s: L('Para cuando los hermanos pelean. Unos 3 minutos.', 'For when siblings fight. About 3 minutes.'),
    b: L([
      '[NARRADOR | calmado, cálido, lento]',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'Junto al río vivía una familia de conejos. Tomi, el mayor, era valiente y rápido. Lía, la pequeña, era alegre y nunca se rendía.',
      'En el parque había un solo columpio. Y los dos lo querían al mismo tiempo.',
      '[PAUSA: corta]',
      'Tomi tiró de la cuerda. Lía también. Sus orejas se pusieron calientes. Sus patas, duras como piedras.',
      'El columpio quedó quieto entre los dos. Nadie se columpiaba.',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'El abuelo conejo se sentó en una roca, cerca. Miró el río un rato.',
      '[ABUELO | lento, tranquilo]',
      '«¿Qué sienten en sus manos ahora?»',
      '[PAUSA: larga]',
      'Lía miró sus patas. Estaban apretadas. Las abrió, despacio.',
      'Sin la cuerda en las manos, sintió el viento. Escuchó el río.',
      'Tomi la miró. Y soltó también.',
      '[PAUSA: corta]',
      'Lía empujó a Tomi, una vez, dos veces, tres. Tomi subía y reía. Después Tomi empujó a Lía, más alto todavía.',
      'El abuelo siguió mirando el río.',
      '[RESPIRA: inhala despacio… exhala despacio]',
      'Esa tarde volvieron a casa con las orejas frescas y las patas suaves. El río seguía sonando, igual que siempre.',
      '[PAUSA: larga]',
    ], [
      '[NARRATOR | calm, warm, slow]',
      '[BREATH: slow inhale… slow exhale]',
      'By the river lived a family of rabbits. Tomi, the eldest, was brave and quick. Lía, the youngest, was cheerful and never gave up.',
      'In the park there was only one swing. And they both wanted it at the same time.',
      '[PAUSE: short]',
      'Tomi pulled the rope. So did Lía. Their ears grew hot. Their paws, hard as stones.',
      'The swing hung still between them. Nobody was swinging.',
      '[BREATH: slow inhale… slow exhale]',
      'Grandfather rabbit sat on a rock nearby. He watched the river for a while.',
      '[GRANDFATHER | slow, quiet]',
      '“What do you feel in your hands right now?”',
      '[PAUSE: long]',
      'Lía looked at her paws. They were clenched. She opened them, slowly.',
      'Without the rope in her hands, she felt the wind. She heard the river.',
      'Tomi looked at her. And he let go too.',
      '[PAUSE: short]',
      'Lía pushed Tomi, once, twice, three times. Tomi rose and laughed. Then Tomi pushed Lía, higher still.',
      'Grandfather kept watching the river.',
      '[BREATH: slow inhale… slow exhale]',
      'That afternoon they walked home with cool ears and soft paws. The river kept singing, the same as always.',
      '[PAUSE: long]',
    ]), reflect: L('¿Qué sintió Lía cuando abrió las manos?', 'What did Lía feel when she opened her hands?'), k: 'pelea fight hermanos siblings compartir share enojo angry turnos turns' },
];

export const PENDING = [
  { t: L('Fines de semana', 'Weekends'), s: L('El ritmo del sábado y domingo, y la práctica de cocina de Sophia.', "The Saturday–Sunday rhythm and Sophia's cooking practice.") },
  { t: L('Protocolo de imprevistos', 'Off-plan protocol'), s: L('El proyecto hermano, situación por situación.', 'The sister project, situation by situation.') },
  { t: L('Dónde duerme cada quien', 'Who sleeps where'), s: L('Se revisa cuando la rutina esté estable y el cuarto esté arreglado.', 'Revisit once the routine is steady and the room is fixed.') },
];
